<?php

namespace App\Services;

use Illuminate\Http\Client\ConnectionException;
use Illuminate\Support\Facades\Log;

class CommentService
{
    /**
     * @throws ConnectionException
     */
    public function post(string $repo, int $index, string $review): bool
    {
        try {
            if (empty($review)) {
                Log::warning('Empty review provided, skipping comment', [
                    'action' => 'comment_empty_review',
                    'business_context' => 'ai_code_review',
                    'repo' => $repo,
                    'pr_number' => $index,
                    'warning_type' => 'empty_content'
                ]);
                return false;
            }

            // Check if the review is an error response from AI provider
            if ($this->isErrorResponse($review)) {
                Log::warning('AI error response detected, skipping comment', [
                    'action' => 'comment_ai_error_response',
                    'business_context' => 'ai_code_review',
                    'repo' => $repo,
                    'pr_number' => $index,
                    'error_response' => $review,
                    'warning_type' => 'ai_error'
                ]);
                return false;
            }

            // Format the review comment
            $formattedReview = $this->formatReview($review);

            $success = app(GiteaService::class)->postComment($repo, $index, $formattedReview);

            if ($success) {
                Log::info('Review comment posted successfully', [
                    'action' => 'comment_posted_success',
                    'business_context' => 'ai_code_review',
                    'repo' => $repo,
                    'pr_number' => $index,
                    'review_length' => strlen($formattedReview)
                ]);
            } else {
                Log::error('Failed to post review comment', [
                    'action' => 'comment_post_failed',
                    'business_context' => 'ai_code_review',
                    'repo' => $repo,
                    'pr_number' => $index,
                    'error_type' => 'post_failure'
                ]);
            }

            return $success;

        } catch (ConnectionException $e) {
            Log::error('Connection error posting review', [
                'action' => 'comment_connection_error',
                'business_context' => 'ai_code_review',
                'repo' => $repo,
                'pr_number' => $index,
                'error' => $e->getMessage(),
                'error_type' => 'connection_error'
            ]);
            throw $e;
        } catch (\Exception $e) {
            Log::error('Error posting review', [
                'action' => 'comment_post_error',
                'business_context' => 'ai_code_review',
                'repo' => $repo,
                'pr_number' => $index,
                'error' => $e->getMessage(),
                'error_type' => 'general_error'
            ]);
            return false;
        }
    }

    private function isErrorResponse(string $review): bool
    {
        // Common error patterns from AI providers
        $errorPatterns = [
            'Claude API error:',
            'OpenAI API error:',
            'Rate limit exceeded',
            'Unable to generate review',
            'API error',
            'connection error',
            'timeout',
            'failed to process',
            'error occurred',
            'service unavailable'
        ];

        // Check if review contains any error patterns
        foreach ($errorPatterns as $pattern) {
            if (stripos($review, $pattern) !== false) {
                return true;
            }
        }

        // Check if review is too short (likely an error message)
        if (strlen(trim($review)) < 50) {
            return true;
        }

        // Check if review looks like a generic error message
        $genericErrorIndicators = [
            'please try again',
            'unable to',
            'failed to',
            'error occurred',
            'something went wrong',
            'internal error'
        ];

        foreach ($genericErrorIndicators as $indicator) {
            if (stripos($review, $indicator) !== false) {
                return true;
            }
        }

        return false;
    }

    private function formatReview(string $review): string
    {
        $timestamp = now()->format('Y-m-d H:i:s');

        return <<<MARKDOWN
## 🤖 AI Code Review

*Generated on: {$timestamp}*

{$review}

---
*This review was generated by AI PR Inspector. Please review the suggestions carefully before applying them.*
MARKDOWN;
    }
}
